<?php
/**
 * Recolize GmbH
 *
 * @section LICENSE
 * This source file is subject to the GNU General Public License Version 3 (GPLv3).
 *
 * @category Recolize
 * @package Recolize_RecommendationEngine
 * @author Recolize GmbH <service@recolize.com>
 * @copyright since 2015 Recolize GmbH (http://www.recolize.com)
 * @license http://opensource.org/licenses/GPL-3.0 GNU General Public License Version 3 (GPLv3).
 */
?>
<?php /** @var \Recolize\RecommendationEngine\Block\CategoryView $this */ ?>
<?php if ($this->helper('Recolize\RecommendationEngine\Helper\Data')->isExtensionEnabled() === true): ?>
    <script type="text/javascript">
        var RecolizeParameters = RecolizeParameters || {};
        RecolizeParameters['specialPageType'] = 'category';
        RecolizeParameters['categoryId'] = '<?php echo $this->getCategory()->getId(); ?>';
    </script>
<?php endif; ?>